<?php
/**
 * Copyright 2016 Maksim Babenko <mb.babenoff@yandex.ru>
 * ContainerTest.php at ld2.my
 * Created by Babenoff at 28.08.16 - 10:59
 */

namespace Test;


use LD2\Container;
use PHPUnit\Framework\TestCase;

class ContainerTest extends TestCase
{
    protected $container;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $container = new Container();
    }
}
