parameters:
  db_engine: "mysql"
  db_user: "ld2"
  db_password: "AaFrv54$5sdf"
  db_host: "localhost"
  db_dbname: "likedimion"

services:
  pdo:
    class: 'LD2\Database'
    arguments: ['%db_user%','%db_password%', '%db_dbname%', '%db_host%', '%db_engine%']

  evd:
    class: 'LD2\EventDispatcher'

  base_pdo_evd_service:
    abstract: true
    calls:
      - [setPdo, ['@pdo']]
      - [setEvd, ['@evd']]
  ld2.registration_service:
    class: 'LD2\Service\RegistrationService'
    calls:
      - [setPdo, ['@pdo']]
      - [setEvd, ['@evd']]

  ld2.user_service:
    class: 'LD2\Service\UserService'
    parent: 'base_pdo_evd_service'
    calls:
      - [setPdo, ['@pdo']]
      - [setEvd, ['@evd']]

  ld2.game_manager:
    class: 'LD2\Manager\GameManagerImpl'
    calls:
      - [setGameService, ['@ld2.game_service']]

  ld2.ai:
    class: 'LD2\Ai'
    calls:
      - [setGameManager, ['@ld2.game_manager']]

  ld2.game_service:
    class: 'LD2\Service\GameService'
    calls:
      - [setPdo,          ['@pdo']]
      #- [setEvd,          ['@evd']]

